# Generated by Django 2.1.10 on 2019-08-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20190811_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'get_latest_by': 'created', 'ordering': ('id',), 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
    ]
