# Generated by Django 2.1.10 on 2019-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20190812_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
