# Generated by Django 2.1.10 on 2019-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leave_approved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
