# Generated by Django 2.1.10 on 2019-08-13 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20190813_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_approve_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
