# Generated by Django 2.1.10 on 2019-08-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_auto_20190814_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick leave', 'Sick leave'), ('Vacation leave', 'Vacation leave'), ('End of employee leave', 'End of Employee leave'), ('Maternity leave', 'Maternity Leave')], default='Sick leave', max_length=30, null=True),
        ),
    ]
