# Generated by Django 2.1.10 on 2019-08-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_auto_20190814_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
