# Generated by Django 2.1.10 on 2019-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20190814_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick leave'), ('vacation', 'Vacation leave'), ('endofemployee', 'End of Employee leave'), ('maternity', 'Maternity Leave')], default='sick', max_length=30, null=True),
        ),
    ]
