# Generated by Django 2.1.10 on 2019-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_auto_20190814_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('endofemployment', 'End of Employment'), ('maternity', 'Maternity')], default='sick', max_length=30, null=True),
        ),
    ]
