# Generated by Django 2.1.10 on 2019-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_auto_20190815_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved_dept_head',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
