# Generated by Django 2.1.10 on 2019-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_leave_approved_dept_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_dept_head',
            field=models.BooleanField(default=False),
        ),
    ]
