# Generated by Django 2.1.10 on 2019-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_auto_20190821_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_declined',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
