# Generated by Django 2.1.10 on 2019-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_leave_is_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='head_declined',
            field=models.BooleanField(default=False),
        ),
    ]
