# Generated by Django 2.1.10 on 2019-08-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0022_leave_head_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
