# Generated by Django 2.1.10 on 2019-08-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
    ]
