# Generated by Django 2.1.10 on 2020-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190811_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assign_days',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
    ]
