# Generated by Django 2.1.10 on 2019-08-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200301_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, default='/media/pics/default_avatar.jpeg', null=True, upload_to='pics'),
        ),
    ]
