# Generated by Django 2.1.10 on 2019-08-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190818_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assign_days',
            field=models.PositiveSmallIntegerField(blank=True, default='/pics/default_avatar.jpeg', null=True),
        ),
    ]
