# Generated by Django 2.1.10 on 2019-08-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190818_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assign_days',
            field=models.PositiveSmallIntegerField(blank=True, default='pics/default_avatar.jpeg', null=True),
        ),
    ]
