# Generated by Django 2.1.10 on 2019-08-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190818_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assign_days',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, default='/pics/default_avatar.jpeg', null=True, upload_to='pics'),
        ),
    ]
