# Generated by Django 2.1.10 on 2019-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190818_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_head',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
