# Generated by Django 2.1.10 on 2019-08-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190821_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='/pics/default_avatar.jpeg', null=True, upload_to='pics'),
        ),
    ]
