# Generated by Django 2.1.10 on 2019-09-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20190822_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-created',), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
